name: Sync LinkedIn Profile Picture

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch LinkedIn profile page
        run: |
          curl -L -H "User-Agent: Mozilla/5.0" \
          https://www.linkedin.com/in/karthik-korrayi/ \
          -o linkedin.html

      - name: Extract profile image URL
        run: |
          IMAGE_URL=$(grep -o 'https://media.licdn.com[^"]*' linkedin.html | head -n 1)

          echo "Found image URL: $IMAGE_URL"

          if [ -z "$IMAGE_URL" ]; then
            echo "Image URL not found."
            exit 1
          fi

          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      - name: Download profile image
        run: |
          curl -L -H "User-Agent: Mozilla/5.0" \
          "$IMAGE_URL" \
          -o public/images/profile.jpg

      - name: Verify image file
        run: |
          file public/images/profile.jpg

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/images/profile.jpg
          git commit -m "Auto update LinkedIn profile picture $(date)" || true
          git push
