name: Sync LinkedIn Profile Picture

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download LinkedIn profile image
        run: |
          curl -L "https://media.licdn.com/dms/image/v2/D5603AQFKBG34d4gFHg/profile-displayphoto-crop_800_800/B56ZzS2k4yKEAI-/0/1773064048892?e=1774483200&v=beta&t=6FKdR6Y_Av3jfgK44wugTSPUFaRzx0Ce5cGgCa_ra5A" -o public/images/profile.jpg

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/images/profile.jpg
          git commit -m "Auto update LinkedIn profile picture $(date)" || true
          git push
